### PR TITLE
Show number of containers

### PR DESCRIPTION
**Pull request by Sanderhuisman**
Show number of containers in each state

### CODE REVIEW

**Comment by ualex73** [comment]
Thanks 👍

**Comment by Sanderhuisman** [comment]
When you are happy I will merge it with the develop branch ;)

**Comment by ualex73** [comment]
Ok, did a quick test ... And it works like a charm 👍 I can see all new container counters.

**Comment by Sanderhuisman** [comment]
Does it actually update if you create a new container? Didn't test this yet ¯\\(ツ)/¯

**Comment by ualex73** [comment]
Did that too, it works. I stop/start/stop/start and did docker rm, docker run, etc ... The counters are correctly going up/down.

**Comment by ualex73** [comment]
If you merge my other pull request, I am happy ;-)

**Pull request merged**
